/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package accurategrabber.server;

import java.awt.Container;
import java.awt.Robot;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import services.ServerService;

/**
 *
 * @author kranti
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    static ServerService serverThread;
    static boolean serverStatus;
    public static Container C;
    public void closeWindow()
    {
        dispose();
    }
    public MainFrame() {
        initComponents();
        serverStatus=serverStatus;
        setSize(Toolkit.getDefaultToolkit().getScreenSize());
        this.setResizable(true);
        C=this.getContentPane();
        
    }
    public MainFrame(ServerService serverThread,boolean serverStatus ) {
        initComponents();
        
        setSize(Toolkit.getDefaultToolkit().getScreenSize());
        this.setResizable(true);
        C=this.getContentPane();
         this.serverStatus=serverStatus;
        this.serverThread=serverThread;
        if(serverStatus==true)
            miStartServer.setText("Stop Server");
        
        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miLogout = new javax.swing.JMenuItem();
        miExit = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        miUserProfile = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miStartServer = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        miProfileReport = new javax.swing.JMenuItem();
        miActivityReport = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("File");

        miLogout.setText("Logout");
        miLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLogoutActionPerformed(evt);
            }
        });
        jMenu1.add(miLogout);

        miExit.setText("Exit");
        miExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miExitActionPerformed(evt);
            }
        });
        jMenu1.add(miExit);

        jMenuBar1.add(jMenu1);

        jMenu5.setText("View");

        miUserProfile.setText("User profile");
        miUserProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miUserProfileActionPerformed(evt);
            }
        });
        jMenu5.add(miUserProfile);

        jMenuBar1.add(jMenu5);

        jMenu2.setText("User Logger");

        miStartServer.setText("Start server");
        miStartServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miStartServerActionPerformed(evt);
            }
        });
        jMenu2.add(miStartServer);

        jMenuBar1.add(jMenu2);

        jMenu6.setText("Report");

        miProfileReport.setText("Profile Report");
        miProfileReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miProfileReportActionPerformed(evt);
            }
        });
        jMenu6.add(miProfileReport);

        miActivityReport.setText("Activity report");
        miActivityReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miActivityReportActionPerformed(evt);
            }
        });
        jMenu6.add(miActivityReport);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 281, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLogoutActionPerformed
        // TODO add your handling code here:
        LoginPage myLoginPage = new LoginPage();
        this.setVisible(false);
        myLoginPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_miLogoutActionPerformed

    private void miExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_miExitActionPerformed

    private void miStartServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miStartServerActionPerformed
        // TODO add your handling code here:
        if(serverStatus==false){
             serverThread = new ServerService();
             serverThread.start();
            miStartServer.setText("Stop Server");
            serverStatus=true;
        }else if(serverStatus==true){
            serverThread.terminate();
           // try {
                //serverThread.join();
                miStartServer.setText("Start Server");
          /*  } catch (InterruptedException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }*/
            serverStatus=false;
        }
        
        
    }//GEN-LAST:event_miStartServerActionPerformed

    private void miUserProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miUserProfileActionPerformed
        // TODO add your handling code here:
        C.removeAll();
        C.setVisible(false);
        ManageUser mu=new ManageUser();
        mu.setBounds(1,1,700,700);
         C.add(mu);
        C.setVisible(true);
    }//GEN-LAST:event_miUserProfileActionPerformed

    private void miProfileReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miProfileReportActionPerformed
        // TODO add your handling code here:
        UserReport ur = new UserReport(serverThread, serverStatus);
        ur.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_miProfileReportActionPerformed

    private void miActivityReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miActivityReportActionPerformed
        // TODO add your handling code here:
        ActivityReport ar = new ActivityReport(serverThread, serverStatus);
        ar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_miActivityReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame(serverThread,serverStatus).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem miActivityReport;
    private javax.swing.JMenuItem miExit;
    private javax.swing.JMenuItem miLogout;
    private javax.swing.JMenuItem miProfileReport;
    private javax.swing.JMenuItem miStartServer;
    private javax.swing.JMenuItem miUserProfile;
    // End of variables declaration//GEN-END:variables
}
